on:
  workflow_dispatch:

jobs:
  display-variables:
    name: teste
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
    - name: Use variables
      run: |
        echo 'teste 1 -- $TESTE1'
        echo "TESTE 2 -- $TESTE2"
      env: 
        TESTE1: ${{ vars.HELLO_WORLD }}
        TESTE2: ${{ vars.TESTE_ENV }}
