on:
  workflow_dispatch:

jobs:
  display-variables:
    name: teste
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo 'Hi ${{ vars.HELLO_WORLD }}'
        echo "TESTE 2 -- ${{ vars.TESTE_ENV }}"
