on:
  workflow_dispatch:

jobs:
  display-variables:
    name: teste
    runs-on: ubuntu-latest
    steps:
    - name: Use variables
      run: |
        echo 'teste 1 -- $TESTE1'
        echo "TESTE 2 -- $TESTE2"
        echo "TESTE 3 -- ${{ env.HELLO_WORLD }}"
        echo "TESTE 4 -- ${{ env.TESTE_ENV }}"
      env: 
        TESTE1: ${{ vars.HELLO_WORLD }}
        TESTE2: ${{ vars.TESTE_ENV }}
